export const jobform = [
    {
      id: 0,
      name: 'title',
      placeholder: 'Job Title',
      type: 'text',
      islabel: true,
      labelTitle: 'Job Title',
      labelClass: 'text-gray-800',
      className: 'bg-white/80 text-gray-900 placeholder-gray-500',
    },
    {
      id: 1,
      name: 'company',
      placeholder: 'Company Name',
      type: 'text',
      islabel: true,
      labelTitle: 'Company',
      labelClass: 'text-gray-800',
      className: 'bg-white/80 text-gray-900 placeholder-gray-500',
    },
    {
      id: 2,
      name: 'description',
      placeholder: 'Job Description',
      type: 'text',
      islabel: true,
      labelTitle: 'Description',
      labelClass: 'text-gray-800',
      className: 'bg-white/80 text-gray-900 placeholder-gray-500',
    },
    {
      id: 3,
      name: 'location',
      placeholder: 'Job Location',
      type: 'text',
      islabel: true,
      labelTitle: 'Location',
      labelClass: 'text-gray-800',
      className: 'bg-white/80 text-gray-900 placeholder-gray-500',
    },
    {
      id: 4,
      name: 'salary',
      placeholder: 'Salary (optional)',
      type: 'text',
      islabel: true,
      labelTitle: 'Salary',
      labelClass: 'text-gray-800',
      className: 'bg-white/80 text-gray-900 placeholder-gray-500',
    },
  ];